// types/index.ts

export interface OrderData {
  id_order?: string; // uuid - generated by DB
  id_user?: string; // uuid - from session
  jenis_layanan: string; // text
  berat_pakaian: number | string; // numeric - use string for input value initially
  metode_pembayaran: string; // text
  alamat_penjemputan: string; // text
  tanggal_pesanan: string; // timestamp without time zone - use string for input value
  total_harga: number | string; // numeric - use string for input value initially
}

export interface PembayaranData {
  id_pembayaran?: string; // uuid - generated by DB
  id_order: string; // uuid - from Order insert result
  id_user: string; // uuid - from session
  metode_pembayaran: string; // text
  jumlah_pembayaran: number; // numeric
  status_pembayaran: string; // text
  diskon_pembayaran: number; // numeric
  tanggal_pembayaran: string; // timestamp without time zone
}

export interface RiwayatData {
  id_riwayat?: string; // uuid - generated by DB
  id_order: string; // uuid - from Order insert result
  id_user: string; // uuid - from session
  status_transaksi: string; // text
  tanggal_transaksi: string; // timestamp without time zone
}
